language: generic 
sudo: required
services:
  - docker
before-install:
  - docker build -t nishanprime/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true nishanprime/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-410333440162"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY